apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: mynamespace
  labels:
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - image: "registryvmo0546.azurecr.io/tripinsights/poi:1.0"
        imagePullPolicy: Always
        name: insurance
        env: 
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SQL_PASSWORD
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SQL_SERVER
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "4000Mi"
            cpu: "100m"
          limits:
            memory: "6000Mi"
            cpu: "1000m"