apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-deployment
  namespace: api
  labels:
    deploy: userjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      containers:
      - image: "registryvmo0546.azurecr.io/tripinsights/user-java:1.0"
        imagePullPolicy: Always
        name: userjava
        env: 
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: mysecretaf
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecretaf
                key: SQL_PASSWORD
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: mysecretaf
                key: SQL_SERVER
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "500Mi"
            cpu: "100m"
          limits:
            memory: "600Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: userjava
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: userjava
  ports:
  - protocol: TCP
    name: userjava-http
    port: 80
    targetPort: 80


