apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: mynamespace
  labels:
    deploy: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - image: "registryvmo0546.azurecr.io/tripinsights/trip-viewer:1.0"
        imagePullPolicy: Always
        name: tripviewer
        env: 
          - name: TRIPS_API_ENDPOINT
            value: http://trips.mynamespace.svc.cluster.local
          - name: USERPROFILE_API_ENDPOINT
            value: http://userprofile.mynamespace.svc.cluster.local
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "500Mi"
            cpu: "100m"
          limits:
            memory: "600Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: mynamespace
spec:
  type: LoadBalancer
  selector:
    app: tripviewer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


