apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: mynamespace
  labels:
    deploy: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - image: "registryvmo0546.azurecr.io/tripinsights/trip-viewer:1.0"
        imagePullPolicy: Always
        name: tripviewer
        env: 
          - name: TRIPS_API_ENDPOINT
            value: trips.mynamespace.svc.cluster.local/8082
          - name: USERPROFILE_API_ENDPOINT
            value: userprofile.mynamespace.svc.cluster.local/8083
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "500Mi"
            cpu: "100m"
          limits:
            memory: "600Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: mynamespace
spec:
  type: LoadBalancer
  selector:
    app: tripviewer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripviewer-ingress
  namespace: mynamespace
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 8081
        path: /tripviewer

